[global]
SHMTU_MACHINE_NAME = ""

[Network]
SHMTU_AUTH_NETWORK_CHECK_RETRY_TIMES = 3
SHMTU_AUTH_NETWORK_CHECK_RETRY_TIME_INTERVAL = 30

[Auth]
SHMTU_AUTH_TIME_INTERVAL = 10

[Notify]
SHMTU_AUTH_WEBHOOK_WEWORK = ""
SHMTU_WEBHOOK_SLEEP_TIME_START = "23:00"
SHMTU_WEBHOOK_SLEEP_TIME_END = "7:00"
