name: PyInstaller Build on Apple macOS(Apple Silicon ARM64)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    # macOS Latest ARM64
    runs-on: macos-latest
    # macOS Latest Intel x64
    # runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Check Version Setting
        run: |
          python --version
          pip --version
          python version.py

      - name: Set Build Info
        run: |
          pip install pytz
          python Build/set_build_info.py -e

      - name: Install dependencies
        run: |
          # pip install -r requirements.txt
          # pip install -r r-dev-requirements.txt
          python install.py all

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: . .\Build\generate_exe_console.ps1

      - name: Make logs directory
        run:
          mkdir ".\Build\shmtu_auth_windows_console\logs"

      - name: Copy Config File
        run:
          cp `
          ".\shmtu_auth\config\config.note.toml" `
          ".\Build\shmtu_auth_windows_console\config.toml"

      - name: Compress Directory to ZIP
        run:
          Compress-Archive `
          -Path ".\Build\shmtu_auth_windows_console" `
          -DestinationPath ".\Build\shmtu_auth_windows_console.zip"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./Build/shmtu_auth_windows_console.zip
