name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      #      - uses: docker/setup-qemu-action@v3
      #      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Aliyun Region
        env:
          ACR_REGION: cn-hangzhou
          ACR_REGISTRY: registry.$ACR_REGION.aliyuncs.com
        run: echo "Aliyun ACR $ACR_REGION"

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
        with:
          login-server: $ACR_REGISTRY
          region-id: $ACR_REGION
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build the Docker image
        env:
          #          IMAGE_TAG: ${{ github.sha }}
          IMAGE_TAG: latest
        run: |
          docker build \
            --file Docker/Dockerfile \
            -t ${{ github.repository }}:$IMAGE_TAG \
            -t registry.cn-hangzhou.aliyuncs.com/${{ github.repository }}:$IMAGE_TAG \
            .

          echo "TAG:${{ github.repository }}:$IMAGE_TAG"

      - name: Push Image to Docker Hub
        run: |
          docker push \
          ${{ github.repository }}:$IMAGE_TAG

      - name: Push Image to Aliyun Container Registry (ACR)
        run: |
          echo "Try to push to $ACR_REGISTRY/${{ github.repository }}:$IMAGE_TAG"
          docker push \
            $ACR_REGISTRY/${{ github.repository }}:$IMAGE_TAG
