name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
        with:
          login-server: registry.cn-shanghai.aliyuncs.com
          region-id: cn-shanghai
#          username: '${{ secrets.ALIYUN_USERNAME }}'
#          password: '${{ secrets.ALIYUN_PASSWORD }}'
          access-key-id: '${{ secrets.ALIYUN_ACCESSKEY_ID }}'
          access-key-secret: '${{ secrets.ALIYUN_ACCESSKEY_SECRET }}'
      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }} # 用于标记容器版本号
        run: |
          docker build \
            --file Docker/Dockerfile \
            -t registry.cn-shanghai.aliyuncs.com/khm_school/shmtu-auth:$IMAGE_TAG \
            .
          docker push \
            registry.cn-shanghai.aliyuncs.com/khm_school/shmtu-auth:$IMAGE_TAG
